"use client"

import { useState } from "react"
import { Sparkles, Loader as Loader2, ShieldCheck, TriangleAlert as AlertTriangle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { TrustScoreCard } from "@/components/trust-score-card"
import { getRiskLevel, type Landlord, type TrustBreakdown } from "@/lib/data"
import { toast } from "sonner"

type ReportResult = {
  score: number
  breakdown: TrustBreakdown
  summary: string
  strengths: string[]
  considerations: string[]
}

export function TrustReportPanel({ landlord }: { landlord: Landlord }) {
  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState<ReportResult | null>(null)

  async function generate() {
    setLoading(true)
    setReport(null)
    try {
      const res = await fetch("/api/trust-score", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: landlord.name,
          role: "landlord",
          breakdown: landlord.trustBreakdown,
          ownershipVerified: landlord.ownershipVerified,
          responseRate: landlord.responseRate,
          rating: landlord.rating,
          reviewCount: landlord.reviewCount,
        }),
      })
      if (!res.ok) throw new Error("Request failed")
      const data = (await res.json()) as ReportResult
      setReport(data)
    } catch {
      toast.error("Could not generate the trust report. Please try again.")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="rounded-2xl border bg-card p-6 shadow-sm">
      <div className="flex items-center gap-2">
        <Sparkles className="size-5 text-primary" aria-hidden />
        <h3 className="font-heading font-semibold">AI Trust Report</h3>
      </div>
      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
        Generate an AI-written summary of this landlord&apos;s verification signals, strengths, and things to consider
        before applying.
      </p>

      {!report && (
        <Button onClick={generate} disabled={loading} className="mt-4 w-full">
          {loading ? (
            <>
              <Loader2 className="size-4 animate-spin" aria-hidden />
              Analyzing signals…
            </>
          ) : (
            <>
              <Sparkles className="size-4" aria-hidden />
              Generate trust report
            </>
          )}
        </Button>
      )}

      {report && (
        <div className="mt-5 space-y-5">
          <TrustScoreCard
            score={report.score}
            subtitle={`${getRiskLevel(report.score)} · AI generated`}
            breakdown={report.breakdown}
          />

          <div>
            <p className="text-sm leading-relaxed text-foreground">{report.summary}</p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="rounded-xl border bg-success/5 p-4">
              <p className="flex items-center gap-1.5 text-sm font-semibold text-success">
                <ShieldCheck className="size-4" aria-hidden />
                Strengths
              </p>
              <ul className="mt-2 space-y-1.5 text-sm text-muted-foreground">
                {report.strengths.map((s, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="text-success">•</span>
                    {s}
                  </li>
                ))}
              </ul>
            </div>
            <div className="rounded-xl border bg-warning/5 p-4">
              <p className="flex items-center gap-1.5 text-sm font-semibold text-warning">
                <AlertTriangle className="size-4" aria-hidden />
                Consider
              </p>
              <ul className="mt-2 space-y-1.5 text-sm text-muted-foreground">
                {report.considerations.map((c, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="text-warning">•</span>
                    {c}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <p className="text-xs text-muted-foreground">
            Generated by AJAR AI from verified signals. Evidence is timestamped and auto-deleted after a rental
            decision.
          </p>
        </div>
      )}
    </div>
  )
}
